fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    tftp: "git://github.com/puppetlabs/puppetlabs-tftp"
    xinetd: "git://github.com/puppetlabs/puppetlabs-xinetd"
    rsync: "git://github.com/puppetlabs/puppetlabs-rsync"
    apache: "git://github.com/puppetlabs/puppetlabs-apache"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    devtools: "git://github.com/Spredzy/puppet-devtools"
    epel: "git://github.com/stahnma/puppet-module-epel"
  symlinks:
    edeploy: "#{source_dir}"
