name    'yguenane-edeploy'
version '0.1.0'
source 'https://github.com/Spredzy/puppet-edeploy'
author 'yguenane'
license 'Apache License, Version 2.0'
summary 'A Puppet module to deploy eDeploy'
description 'A Puppet module to deploy eDeploy'
project_page 'https://github.com/Spredzy/puppet-edeploy'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '= 4.1.0'
dependency 'puppetlabs/tftp', '= 0.2.1'
dependency 'puppetlabs/rsync', '= 0.1.0'
dependency 'puppetlabs/apache', '= 0.9.0'
dependency 'stahnma/epel', '= 0.0.5'
dependency 'yguenane/devtools', '= 0.1.0'
dependency 'puppetlabs/apt', '= 1.4.1'
